############################################################
# +------------------------------------------------------+ #
# |             Simple Player Authentication             | #
# +------------------------------------------------------+ #
############################################################

########################
#Basic Settings
########################

#Minimal length you want the passwords to be (0 = no minimal).
minimal-password-length: 4

#Have the players use numbers in their password.
numbers-in-password-required: true

#The amount of attempts that can be made to login.
login-attempts: 3

#What happens after failing the maximum attempts
punishment: "kick %PLAYERNAME% §cYou have reached maximum login attempts"

########################
#Advanced Settings
########################

# Attention! These are more complicated settings that are better left alone if you do not understand them!

#Which algorithm has to be used for hashing the password.
#Available algorithms: argon2, scrypt, bcrypt, pbkdf2
hashing-algorithm: "argon2"

#Which repository has to be used to store the accounts.
# Available repositories: yaml
repository-type: "yaml"