main: com.skywalx.simpleplayerauthentication.SimplePlayerAuthenticationPlugin
version: 1.1.0
api-version: 1.17
name: SimplePlayerAuthentication
description: Simple plugin that enables an extra authentication layer within the Minecraft server.
author: Skywalx
website: www.skywalx.com
softdepend:
  - PlaceholderAPI