name: Release

on:
  push:
    branches: [ "feature/github-workflow" ]
  pull_request:
    branches: [ "feature/github-workflow" ]

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: simple-player-authentication.zip
        path: build/libs/simple-player-authentication-*-all.jar

    - name: Release the Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/simple-player-authentication-*-all.jar
        asset_name: simple-player-authentication.jar
        asset_content_type: application/java-archive
